/**
 * Reading the published forecast artifacts.
 *
 * The frontend reads JSON that the Python pipeline wrote — it never computes
 * a probability of its own. That separation is deliberate and load-bearing:
 * a number rendered on the page must be traceable to a specific artifact,
 * generated by a specific model version, from a specific corpus. A component
 * that quietly recomputes something is a second model nobody benchmarked.
 *
 * Every accessor here returns `null` rather than a default when the artifact
 * is missing. **Absent data is rendered as absent**, never as zero — a 0%
 * championship probability and "we have not run the forecast" look identical
 * on a page and mean completely different things.
 */

import fs from 'node:fs'
import path from 'node:path'

const PREDICTIONS_DIR = path.join(process.cwd(), 'backend', 'data', 'predictions')
const DIAGNOSTICS_DIR = path.join(process.cwd(), 'backend', 'data', 'diagnostics')

export interface TeamProjection {
  team_id: number
  name: string
  conference: string
  wins: number
  losses: number
  wins_p10: number
  wins_p90: number
  p_playoffs: number
  p_play_in: number
  p_top_seed: number
  p_conf_semis: number
  p_conf_finals: number
  p_conference_title: number
  p_championship: number
  seed_distribution: Record<string, number>
  current_wins: number
  current_losses: number
  games_left: number
  elo: number
}

export interface MeasuredBlock {
  available: boolean
  reason?: string
  generated_at?: string
  walk_forward_n?: number
  walk_forward_brier?: number
  walk_forward_ece?: number
  paired_n?: number
  market_brier?: number
  model_brier?: number
  gap_to_market?: number
  bootstrap?: {
    mean_diff: number
    ci_low: number
    ci_high: number
    p_a_better: number
  }
  basis?: string
}

export interface SeasonProjections {
  season: number
  simulations: number
  games_played: number
  games_remaining: number
  generated_at: string
  model_version: string
  teams: TeamProjection[]
  measured: MeasuredBlock
}

export interface GameSide {
  team_id: number
  name: string
  abbreviation: string
  conference: string
  logo: string | null
  elo: number
}

export interface ValueSurface {
  ml_home: number
  ml_away: number
  fair_home: number
  fair_away: number
  overround: number
  spread_home: number | null
  total_points: number | null
  edge_home: number
  edge_away: number
  best_side: 'home' | 'away'
  edge: number
  expected_value: number
  kelly: number
  flagged: boolean
  min_edge: number
}

export interface GameForecast {
  game_id: string
  date_utc: string
  venue: string | null
  neutral_site: boolean
  home: GameSide
  away: GameSide
  p_home: number
  p_away: number
  exp_margin: number
  exp_total: number
  exp_home_score: number
  exp_away_score: number
  margin_sd: number
  total_sd: number
  value?: ValueSurface
}

export interface GameForecasts {
  season: number
  generated_at: string
  model_version: string
  n_games: number
  n_priced: number
  n_flagged: number
  min_edge: number
  games: GameForecast[]
}

export interface PowerRating {
  rank: number
  team_id: number
  name: string
  abbreviation: string
  conference: string
  logo: string | null
  elo: number
}

export interface PowerRatings {
  season: number
  generated_at: string
  model_version: string
  teams: PowerRating[]
}

function readJson<T>(dir: string, file: string): T | null {
  try {
    const raw = fs.readFileSync(path.join(dir, file), 'utf8')
    return JSON.parse(raw) as T
  } catch {
    // A missing or unparseable artifact is a real, reportable state — the
    // pipeline has not run, or it crashed mid-write. Callers render "no
    // forecast published" rather than an empty table that looks like a
    // forecast of nothing.
    return null
  }
}

export function getSeasonProjections(): SeasonProjections | null {
  return readJson<SeasonProjections>(PREDICTIONS_DIR, 'season_projections.json')
}

export function getGameForecasts(): GameForecasts | null {
  return readJson<GameForecasts>(PREDICTIONS_DIR, 'game_forecasts.json')
}

export function getPowerRatings(): PowerRatings | null {
  return readJson<PowerRatings>(PREDICTIONS_DIR, 'power_ratings.json')
}

/* ------------------------------------------------------ playoff bracket */

export interface BracketSeed {
  seed: number
  p_seed: number
  team_id: number
  name: string
  abbreviation: string | null
  logo: string | null
  wins: number
  losses: number
}

export interface BracketSide {
  team_id: number
  name: string | null
  abbreviation: string | null
  logo: string | null
  wins: number | null
  losses: number | null
  elo: number
  p_seed: number
}

export interface ProjectedSeries {
  high_seed: number
  low_seed: number
  high: BracketSide
  low: BracketSide
  p_high_game_home: number
  p_high_game_away: number
  p_high_series: number
  p_low_series: number
  modal_length: number | null
  lengths: Record<string, number>
}

export interface RoundReach {
  team_id: number
  name: string
  abbreviation: string | null
  logo: string | null
  conference: string
  p_playoffs: number
  p_conf_semis: number
  p_conf_finals: number
  p_finals: number
  p_title: number
}

export interface ProjectedBracket {
  season: number
  generated_at: string
  model_version: string
  simulations: number
  games_played: number
  basis: string
  conferences: Record<
    string,
    { seeds: BracketSeed[]; first_round: ProjectedSeries[] }
  >
  rounds: RoundReach[]
  note: string
}

export function getProjectedBracket(): ProjectedBracket | null {
  return readJson<ProjectedBracket>(PREDICTIONS_DIR, 'playoff_bracket.json')
}

export function getMarketBenchmark(): Record<string, unknown> | null {
  return readJson(DIAGNOSTICS_DIR, 'market_benchmark.json')
}

export function getSeriesModel(): Record<string, unknown> | null {
  return readJson(DIAGNOSTICS_DIR, 'series_model.json')
}

export function getEloSweep(): Record<string, unknown> | null {
  return readJson(DIAGNOSTICS_DIR, 'elo_sweep.json')
}

/** Games grouped by their Eastern calendar date, in schedule order. */
export function groupByDay(games: GameForecast[]): Array<[string, GameForecast[]]> {
  const buckets = new Map<string, GameForecast[]>()
  for (const game of games) {
    // Bucketed on the US Eastern day, matching how the league itself talks
    // about a slate. A UTC bucket splits a normal evening across two dates.
    const day = new Date(new Date(game.date_utc).getTime() - 5 * 3600 * 1000)
      .toISOString()
      .slice(0, 10)
    const existing = buckets.get(day)
    if (existing) existing.push(game)
    else buckets.set(day, [game])
  }
  return Array.from(buckets.entries()).sort((a, b) => a[0].localeCompare(b[0]))
}
